### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by abhishek-das-ind** [coderQuad/New-Grad-Positions-2023#649]
### Improvement

I believe it would be beneficial to include the required skills for the job role directly within the table in this repository.

**Comment by hwuiwon** [comment]
That would be bad for readability.

**Comment by abhishek-das-ind** [comment]
> That would be bad for readability.

Yes but I recommend a redesign that presents the required skills for the job role within the table in a more organized and easily readable format.

**Comment by cwcoogan** [comment]
Thanks for the suggestion, we will take this into consideration. At the current state of the repository this may not be feasible due to the never-ending list of requirements some companies are asking for. In the future-state, we may approve this and limit the number of skills required to <= 7-10 traits.
